name: saadoun
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  camera: ^0.11.0  
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.0
  shared_preferences: ^2.0.8
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.3.0
  url_launcher: ^6.3.0
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.2.8
  mailer: ^6.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  file_picker: ^8.0.7
  device_info_plus: ^10.1.2
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/app_icon.png"

flutter:
  # Cette ligne doit être dans la section "flutter"
  uses-material-design: true

  assets:
    - lib/assets/download.gif
