// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt629C9YyVqpm3yG4ro8MskgMqRY37hgI',
    appId: '1:922795254650:web:08defb0233ed6be7f9acc3',
    messagingSenderId: '922795254650',
    projectId: 'login-e6dc3',
    authDomain: 'login-e6dc3.firebaseapp.com',
    storageBucket: 'login-e6dc3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb-iom6SDXlwpOFZsAFZD-Z0vs2HBEVtM',
    appId: '1:922795254650:android:86fdc49ddd73d983f9acc3',
    messagingSenderId: '922795254650',
    projectId: 'login-e6dc3',
    storageBucket: 'login-e6dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHrT7Lr9GEcCbgPpnUmStFOkSMMq0Y7WM',
    appId: '1:922795254650:ios:cc1b29c3869345d4f9acc3',
    messagingSenderId: '922795254650',
    projectId: 'login-e6dc3',
    storageBucket: 'login-e6dc3.appspot.com',
    iosBundleId: 'com.example.saadoun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHrT7Lr9GEcCbgPpnUmStFOkSMMq0Y7WM',
    appId: '1:922795254650:ios:cc1b29c3869345d4f9acc3',
    messagingSenderId: '922795254650',
    projectId: 'login-e6dc3',
    storageBucket: 'login-e6dc3.appspot.com',
    iosBundleId: 'com.example.saadoun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt629C9YyVqpm3yG4ro8MskgMqRY37hgI',
    appId: '1:922795254650:web:397a7e136dddc521f9acc3',
    messagingSenderId: '922795254650',
    projectId: 'login-e6dc3',
    authDomain: 'login-e6dc3.firebaseapp.com',
    storageBucket: 'login-e6dc3.appspot.com',
  );

}